// Code generated by protoc-gen-connect-swift. DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Source: worker/v1/worker.proto
//

import Connect
import Foundation
import SwiftProtobuf

public protocol Worker_V1_WorkerServiceClientInterface: Sendable {

    @available(iOS 13, *)
    func `info`(request: Worker_V1_InfoRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_InfoResponse>

    @available(iOS 13, *)
    func `execute`(request: Worker_V1_ExecuteRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_ExecuteResponse>

    @available(iOS 13, *)
    func `listJobs`(request: Worker_V1_ListJobsRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_ListJobsResponse>

    @available(iOS 13, *)
    func `watchJob`(headers: Connect.Headers) -> any Connect.ServerOnlyAsyncStreamInterface<Worker_V1_WatchJobRequest, Worker_V1_WatchJobResponse>

    @available(iOS 13, *)
    func `jobOutput`(request: Worker_V1_JobOutputRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_JobOutputResponse>

    @available(iOS 13, *)
    func `jobWait`(request: Worker_V1_JobWaitRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_JobWaitResponse>

    @available(iOS 13, *)
    func `jobStdin`(request: Worker_V1_JobStdinRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_JobStdinResponse>

    @available(iOS 13, *)
    func `jobKill`(request: Worker_V1_JobKillRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_JobKillResponse>

    @available(iOS 13, *)
    func `fileRead`(request: Worker_V1_FileReadRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_FileReadResponse>

    @available(iOS 13, *)
    func `fileWrite`(request: Worker_V1_FileWriteRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_FileWriteResponse>

    @available(iOS 13, *)
    func `fileList`(request: Worker_V1_FileListRequest, headers: Connect.Headers) async -> ResponseMessage<Worker_V1_FileListResponse>
}

/// Concrete implementation of `Worker_V1_WorkerServiceClientInterface`.
public final class Worker_V1_WorkerServiceClient: Worker_V1_WorkerServiceClientInterface, Sendable {
    private let client: Connect.ProtocolClientInterface

    public init(client: Connect.ProtocolClientInterface) {
        self.client = client
    }

    @available(iOS 13, *)
    public func `info`(request: Worker_V1_InfoRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_InfoResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/Info", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `execute`(request: Worker_V1_ExecuteRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_ExecuteResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/Execute", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `listJobs`(request: Worker_V1_ListJobsRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_ListJobsResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/ListJobs", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `watchJob`(headers: Connect.Headers = [:]) -> any Connect.ServerOnlyAsyncStreamInterface<Worker_V1_WatchJobRequest, Worker_V1_WatchJobResponse> {
        return self.client.serverOnlyStream(path: "/worker.v1.WorkerService/WatchJob", headers: headers)
    }

    @available(iOS 13, *)
    public func `jobOutput`(request: Worker_V1_JobOutputRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_JobOutputResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/JobOutput", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `jobWait`(request: Worker_V1_JobWaitRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_JobWaitResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/JobWait", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `jobStdin`(request: Worker_V1_JobStdinRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_JobStdinResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/JobStdin", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `jobKill`(request: Worker_V1_JobKillRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_JobKillResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/JobKill", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `fileRead`(request: Worker_V1_FileReadRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_FileReadResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/FileRead", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `fileWrite`(request: Worker_V1_FileWriteRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_FileWriteResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/FileWrite", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    @available(iOS 13, *)
    public func `fileList`(request: Worker_V1_FileListRequest, headers: Connect.Headers = [:]) async -> ResponseMessage<Worker_V1_FileListResponse> {
        return await self.client.unary(path: "/worker.v1.WorkerService/FileList", idempotencyLevel: .unknown, request: request, headers: headers)
    }

    public enum Metadata {
        public enum Methods {
            public static let info = Connect.MethodSpec(name: "Info", service: "worker.v1.WorkerService", type: .unary)
            public static let execute = Connect.MethodSpec(name: "Execute", service: "worker.v1.WorkerService", type: .unary)
            public static let listJobs = Connect.MethodSpec(name: "ListJobs", service: "worker.v1.WorkerService", type: .unary)
            public static let watchJob = Connect.MethodSpec(name: "WatchJob", service: "worker.v1.WorkerService", type: .serverStream)
            public static let jobOutput = Connect.MethodSpec(name: "JobOutput", service: "worker.v1.WorkerService", type: .unary)
            public static let jobWait = Connect.MethodSpec(name: "JobWait", service: "worker.v1.WorkerService", type: .unary)
            public static let jobStdin = Connect.MethodSpec(name: "JobStdin", service: "worker.v1.WorkerService", type: .unary)
            public static let jobKill = Connect.MethodSpec(name: "JobKill", service: "worker.v1.WorkerService", type: .unary)
            public static let fileRead = Connect.MethodSpec(name: "FileRead", service: "worker.v1.WorkerService", type: .unary)
            public static let fileWrite = Connect.MethodSpec(name: "FileWrite", service: "worker.v1.WorkerService", type: .unary)
            public static let fileList = Connect.MethodSpec(name: "FileList", service: "worker.v1.WorkerService", type: .unary)
        }
    }
}
